format = """
\n\
$directory\
$time\
$git_branch\
$git_metrics\
\n\
$character\
"""

add_newline = false

[package]
disabled = true

[directory]
style = 'bold blue'
truncation_length = 5
truncation_symbol = ".../"
truncate_to_repo = false
read_only = " 󰌾" #鍵のicon

[time]
style = "bold white"
format = '[\[](bold yellow)[$time]($style)[\]](bold yellow)'
disabled = false

[git_branch]
truncation_length = 4
truncation_symbol = ''
format = ' [$symbol$branch(:$remote_branch)]($style)'

[git_metrics]
added_style = 'green'
deleted_style = 'red'
format = ' [+$added]($added_style)/[-$deleted]($deleted_style)'
disabled = false

[character]
error_symbol = "[❯](bold red)"
success_symbol = "[❯](bold red)"
